[default]
logLevel=2
bLogClear=1 ;clear log file on start

base=[1000, 0, 0, 0; 0, 1000, 0, 0; 0, 0, 1000, 0; 0, 0, 1000, 1]
;base=[1000, 0, 0, 0; 0, 0, 1000, 0; 0, -1000, 0, 0; 0, 0, 0, 1]

near=0.0100
far=1000.00000
screen=2.00000

autoViewC=1.00000;
bAutoView=1;
bTurnWithView=1
port=8080
;addr=192.168.0.1
heartBeatPort=3000
calibFile=warp.vwf
;enable next to simulate head-tracking input, if your application does not provide this
;make sure to call VWB_getView.. each frame in pre-render stage
;eyePointProvider=EyePointProvider
eyePointProviderParam=listen 1998
ndiCalibStream=*

[Display1]
calibFile=vwfvioso\25channel_192.168.50.101.vwf
[Display2]
calibFile=vwfvioso\25channel_192.168.50.102.vwf
[Display3]
calibFile=vwfvioso\25channel_192.168.50.103.vwf
[Display4]
calibFile=vwfvioso\25channel_192.168.50.104.vwf
[Display5]
calibFile=vwfvioso\25channel_192.168.50.105.vwf
[Display6]
calibFile=vwfvioso\25channel_192.168.50.106.vwf
[Display7]
calibFile=vwfvioso\25channel_192.168.50.107.vwf
[Display8]
calibFile=vwfvioso\25channel_192.168.50.108.vwf
[Display9]
calibFile=vwfvioso\25channel_192.168.50.109.vwf
[Display10]
calibFile=vwfvioso\25channel_192.168.50.110.vwf
[Display11]
calibFile=vwfvioso\25channel_192.168.50.111.vwf
[Display12]
calibFile=vwfvioso\25channel_192.168.50.112.vwf
[Display13]
calibFile=vwfvioso\25channel_192.168.50.113.vwf
[Display14]
calibFile=vwfvioso\25channel_192.168.50.114.vwf
[Display15]
calibFile=vwfvioso\25channel_192.168.50.115.vwf
[Display16]
calibFile=vwfvioso\25channel_192.168.50.116.vwf
[Display17]
calibFile=vwfvioso\25channel_192.168.50.117.vwf
[Display18]
calibFile=vwfvioso\25channel_192.168.50.118.vwf
[Display19]
calibFile=vwfvioso\25channel_192.168.50.119.vwf
[Display20]
calibFile=vwfvioso\25channel_192.168.50.120.vwf
[Display21]
calibFile=vwfvioso\25channel_192.168.50.121.vwf
[Display22]
calibFile=vwfvioso\25channel_192.168.50.122.vwf
[Display23]
calibFile=vwfvioso\25channel_192.168.50.123.vwf
[Display24]
calibFile=vwfvioso\25channel_192.168.50.124.vwf
[Display25]
calibFile=vwfvioso\25channel_192.168.50.125.vwf
