[default]
logLevel=2
bLogClear=1 ;clear log file on start

; use with right-handed (most openGL/Vulcan) coordinate system
trans=[1000,0,0,0; 0,1000,0,0; 0,0,1000,0; 0,0,0,1]
eye=[0,0,0]

near=0.1 ; the minimum rendering distance, all faces closer than that are culled
far=20000 ; the maximum rendering disctance, all faces futher than that are culled

bTurnWithView=1 ; set to true, if moving platform alas world turns with view direction
bUseGL110=0 ; enable to use with fixed-pipeline openGL
bicubic=0 ; set to true to enhance sampling acuracy, will use up some extra GPU
mouseMode=0
autoViewC=1 ;if viewplane is skewed, widen FoV to cover a moving range of autoViewC * screen
bAutoView=1 ;overwrites screen fov and dir

;calibFile=panadome_3x1_portrait.vwf
calibFile=manu3D.vwf

;enable next to simulate head-tracking input, if your application does not provide this
;make sure to call VWB_getView.. each frame in pre-render stage and use the received parameters to render your scene
eyePointProvider=EyePointProvider
eyePointProviderParam=listen 1998

[Display1]
calibIndex=0 ;left

[Display2] 
calibIndex=1 ;center

[Display3]
calibIndex=2 ;right
