[default]
logLevel=2
bLogClear=1 ;clear log file on start

//base=[1000, 0, 0, 0; 0, 1000, 0, 0; 0, 0, 1000, 0; 0, 0, 1000, 1]
base=[1000, 0, 0, 0; 0, 0, 1000, 0; 0, -1000, 0, 0; 0, 0, 0, 1]

near=0.0100
far=1000.00000
screen=2.00000

autoViewC=1.00000;
bAutoView=1;
bTurnWithView=1
port=8080
addr=192.168.0.1
heartBeatPort=3000
calibFile=vioso3d.vwf
;enable next to simulate head-tracking input, if your application does not provide this
;make sure to call VWB_getView.. each frame in pre-render stage
eyePointProvider=EyePointProvider
eyePointProviderParam=listen 1998


[Display1]
calibIndex=0 ;left
;calibFile=cylindric1of8.vwf

bIndex=0