cmake_minimum_required(VERSION 3.9)

project(VIOSOWarpBlend VERSION 1.6.24 DESCRIPTION "VIOSOWarpBlend library" LANGUAGES CXX C)

set(OpenGL_GL_PREFERENCE GLVND)
find_package(OpenGL REQUIRED)
include_directories(${OpenGL_INCLUDE_DIRS})
add_definitions(${OpenGL_DEFINITIONS})
if(NOT OPENGL_FOUND)
  message(ERROR "OPENGL not found!")
endif(NOT OPENGL_FOUND)

set( SOURCES logging.cpp PathHelper.cpp VIOSOWarpBlend.cpp VWF.cpp 3rdparty/aes/aes.c 3rdparty/tinyxml2/tinyxml2.cpp GL/GLWarpBlend.cpp GL/GLWarpBlendXPL.cpp)

if(WIN32)
    set( SOURCES ${SOURCES}  DX/DXWarpBlend.cpp DX/DX9EXWarpBlend.cpp DX/DX9WarpBlend.cpp DX/DX10WarpBlend.cpp DX/DX11WarpBlend.cpp DX/DX12WarpBlend.cpp )
    if(CMAKE_SIZEOF_VOID_P EQUAL 4)
        set(ARCH_POSTFIX "")
            set(LIB_ARCH_PATH "Win32")
            set(LIB_EXTENSION "")
    else()
            set(ARCH_POSTFIX 64)
            set(LIB_ARCH_PATH "x64")
            set(LIB_EXTENSION "64")
    endif()
else()
    set(ARCH_POSTFIX "")
    set( ${CMAKE_CXX_FLAGS} ${CMAKE_CXX_FLAGS} -g -Wall -Woverloaded-virtual -Wno-parentheses -O2 -fPIC)
endif(WIN32)

add_library(VIOSOWarpBlend SHARED ${SOURCES} )
set_property(TARGET VIOSOWarpBlend PROPERTY CXX_STANDARD 20)
if(WIN32)
    target_link_libraries (VIOSOWarpBlend opengl32 glu32)
else()
    target_link_libraries (VIOSOWarpBlend GL GLU libdl.so )
    target_link_options(VIOSOWarpBlend BEFORE PRIVATE "-rdynamic")
endif(WIN32)
set_target_properties(VIOSOWarpBlend PROPERTIES ENABLE_EXPORTS 1)
include_directories(${CMAKE_SOURCE_DIR}/Include)
