TOPDIR = ../../..
SOURCES = logging.cpp linux_compat.cpp PathHelper.cpp VIOSOWarpBlend.cpp VWF.cpp LoadDAE.cpp GL/GLWarpBlend.cpp 3rdparty/delauney/DelaunayTriangles.cpp \
			3rdparty/tinyxml2/tinyxml2.cpp
INTSUBDIRS = GL 3rdparty/delauney 3rdparty/tinyxml2
DYNLIB = VIOSOWarpBlend
INCPATHS = 
CXXFLAGS = 
SYSLIBS = -lGL -lGLU -lGLEW -ldl


include $(TOPDIR)/SILABMAKE/make/make.dynlib
